# Generated by Django 4.0.1 on 2022-01-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_number_item_article_no_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=None),
        ),
    ]
